spring:
  application:
    name: spring-cloud-dubbo1-comsumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8024
dubbo:
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.cly.springcloud.*
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services: spring-cloud-dubbo1-provider
