spring:
  application:
    name: springcloud-dubbo-comsumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8023
dubbo:
  registry:
    address: spring-cloud://127.0.0.1
  protocol:
    port: -1
    name: dubbo
  cloud:
    subscribed-services: springcloud-dubbo
  application:
    qos-accept-foreign-ip: false
    qos-enable: true
    qos-port: 3333